import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/cug3dua.css" />
      </head>
      <body
        className="antialiased font-sans bg-whippedCream text-leafyGreen-default"
      >
        {children}
      </body>
    </html>
  );
}
